#!/bin/bash

echo "************ Cronny Started ***************"
date >> ${OPENSHIFT_DATA_DIR}/wen-start.log

#source ${OPENSHIFT_HOMEDIR}/python/virtenv/bin/activate
cd ${OPENSHIFT_HOMEDIR}/data
python xinwen.py clean 7

echo "************ Cronny Executed ***************"
date >> ${OPENSHIFT_DATA_DIR}/wen-end.log
