#!/bin/bash

hour=$(date '+%H')
if [ $hour = 18 -o $hour = 15 ] ; then
    echo "************ Cronny Started ***************"
    date >> ${OPENSHIFT_DATA_DIR}/test-start.log
    #source ${OPENSHIFT_HOMEDIR}/python/virtenv/bin/activate
    cd ${OPENSHIFT_REPO_DIR}data
    python xinwen.py wenxue

    echo "************ Cronny Executed ***************"
    date >> ${OPENSHIFT_DATA_DIR}/test-end.log

else
    exit

fi
